"use client";
import { useState, useEffect, useCallback } from "react";
const fmt = (n) => "$" + Number(n || 0).toLocaleString();
const ROLES = { admin: "👑 總部", manager: "🏠 管理", staff: "👤 員工" };
const DAYS = ["日","一","二","三","四","五","六"];
const LT = { annual:{l:"特休",c:"#4361ee",bg:"#e6f1fb"}, sick:{l:"病假",c:"#b45309",bg:"#fff8e6"}, personal:{l:"事假",c:"#8a6d00",bg:"#fef9c3"}, menstrual:{l:"生理假",c:"#993556",bg:"#fbeaf0"}, off:{l:"例假",c:"#666",bg:"#f0f0f0"}, rest:{l:"休息日",c:"#888",bg:"#f5f5f5"} };
function api(u,b){return b?fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)}).then(r=>r.json()):fetch(u).then(r=>r.json());}
function Badge({status}){const m={matched:{bg:"#e6f9f0",c:"#0a7c42"},minor_diff:{bg:"#fff8e6",c:"#8a6d00"},anomaly:{bg:"#fde8e8",c:"#b91c1c"},pending:{bg:"#f0f0f0",c:"#666"},approved:{bg:"#e6f9f0",c:"#0a7c42"},rejected:{bg:"#fde8e8",c:"#b91c1c"}};const s=m[status]||m.pending;return <span style={{padding:"2px 6px",borderRadius:8,fontSize:10,background:s.bg,color:s.c}}>{status}</span>;}
function RB({role}){const c={admin:{bg:"#fde8e8",c:"#b91c1c"},manager:{bg:"#e6f1fb",c:"#185fa5"},staff:{bg:"#e6f9f0",c:"#0a7c42"}};const s=c[role]||c.staff;return <span style={{padding:"1px 5px",borderRadius:5,fontSize:9,background:s.bg,color:s.c}}>{ROLES[role]}</span>;}

export default function Admin(){
  const [tab,setTab]=useState("schedules");const[stores,setStores]=useState([]);const[sf,setSf]=useState("");
  const[month,setMonth]=useState(()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;});
  const[sv,setSv]=useState("week");const[stl,setStl]=useState([]);const[sum,setSum]=useState({});const[dep,setDep]=useState([]);
  const[emps,setEmps]=useState([]);const[shifts,setShifts]=useState([]);const[scheds,setScheds]=useState([]);
  const[att,setAtt]=useState([]);const[as,setAs]=useState({});const[lr,setLr]=useState([]);const[ld,setLd]=useState(false);
  const[si,setSi]=useState(null);const[saf,setSaf]=useState(false);const[ne,setNe]=useState({name:"",store_id:"",role:"staff",phone:""});
  const[nbc,setNbc]=useState(null);const[ssf,setSsf]=useState(false);const[es,setEs]=useState(null);
  const[sf2,setSf2]=useState({store_id:"",name:"",start_time:"10:00",end_time:"20:00",break_minutes:60,work_hours:9,role:"all"});
  const[ws,setWs]=useState(()=>{const d=new Date();d.setDate(d.getDate()-d.getDay()+1);return d.toLocaleDateString("sv-SE");});
  const[pm,setPm]=useState(null);

  useEffect(()=>{api("/api/admin/stores").then(d=>setStores(d.data||[]));},[]);

  const load=useCallback(()=>{
    setLd(true);const p=new URLSearchParams();if(month)p.set("month",month);if(sf)p.set("store_id",sf);
    const we2=new Date(new Date(ws).getTime()+6*86400000).toLocaleDateString("sv-SE");
    const sp=sv==="week"?`week_start=${ws}&week_end=${we2}${sf?`&store_id=${sf}`:""}`:`month=${month}${sf?`&store_id=${sf}`:""}`;
    Promise.all([api(`/api/admin/settlements?${p}`),api(`/api/admin/deposits?${p}`),api("/api/admin/employees"),api(`/api/admin/shifts${sf?`?store_id=${sf}`:""}`),api(`/api/admin/schedules?${sp}`),api(`/api/admin/attendance?type=records&${p}`),api("/api/admin/attendance?type=settings"),api(`/api/admin/leaves?${p}`)]).then(([s,d,e,sh,sc,at2,as2,lr2])=>{setStl(s.data||[]);setSum(s.summary||{});setDep(d.data||[]);setEmps(e.data||[]);setShifts(sh.data||[]);setScheds(sc.data||[]);setAtt(at2.data||[]);setAs(as2.data||{});setLr(lr2.data||[]);setLd(false);});
  },[month,sf,ws,sv]);
  useEffect(()=>{load();},[load]);

  const addEmp=async()=>{const d=await api("/api/admin/employees",{action:"create",...ne});if(d.bind_code){setNbc(d.bind_code);load();}};
  const regen=async(id)=>{const d=await api("/api/admin/employees",{action:"generate_bind_code",employee_id:id});if(d.bind_code)alert("綁定碼："+d.bind_code);load();};
  const saveShift=async()=>{if(es)await api("/api/admin/shifts",{action:"update",shift_id:es,...sf2});else await api("/api/admin/shifts",{action:"create",...sf2});setSsf(false);setEs(null);load();};
  const delShift=async(id)=>{if(confirm("刪除？")){await api("/api/admin/shifts",{action:"delete",shift_id:id});load();}};
  const editShift=(s)=>{setEs(s.id);setSf2({store_id:s.store_id,name:s.name,start_time:s.start_time,end_time:s.end_time,break_minutes:s.break_minutes,work_hours:s.work_hours,role:s.role});setSsf(true);};
  const addSch=async(eid,sid,date)=>{const sh=shifts.find(s=>s.id===sid);await api("/api/admin/schedules",{action:"create",employee_id:eid,store_id:sh?.store_id||sf,shift_id:sid,date});load();};
  const addLv=async(eid,date,lt,hd)=>{await api("/api/admin/schedules",{action:"add_leave",employee_id:eid,date,leave_type:lt,half_day:hd||null});load();};
  const delSch=async(id)=>{await api("/api/admin/schedules",{action:"delete",schedule_id:id});load();};
  const pub=async()=>{const we2=new Date(new Date(ws).getTime()+6*86400000).toLocaleDateString("sv-SE");const d=await api("/api/admin/schedules",{action:"publish",week_start:ws,week_end:we2,store_id:sf||undefined});setPm(`發布${d.published||0}筆，通知${d.notified||0}人`);setTimeout(()=>setPm(null),5000);load();};
  const rvLv=async(id,st)=>{await api("/api/admin/leaves",{action:"review",request_id:id,status:st});load();};
  const upS=(k,v)=>{setAs({...as,[k]:v});clearTimeout(window._st);window._st=setTimeout(()=>api("/api/admin/attendance",{action:"update_settings",[k]:v}),1000);};

  const wd=Array.from({length:7},(_,i)=>new Date(new Date(ws).getTime()+i*86400000).toLocaleDateString("sv-SE"));
  const prevW=()=>setWs(new Date(new Date(ws).getTime()-7*86400000).toLocaleDateString("sv-SE"));
  const nextW=()=>setWs(new Date(new Date(ws).getTime()+7*86400000).toLocaleDateString("sv-SE"));

  const getMD=()=>{const[y,m]=month.split("-").map(Number);const f=new Date(y,m-1,1);const sd=f.getDay();const ds=[];for(let i=-sd;i<42-sd&&ds.length<42;i++){const d=new Date(y,m-1,1+i);ds.push({date:d.toLocaleDateString("sv-SE"),inM:d.getMonth()===m-1});}return ds;};

  const ae=emps.filter(e=>e.is_active);const fe=sf?ae.filter(e=>e.store_id===sf||e.role==="admin"):ae;
  const pl=lr.filter(l=>l.status==="pending");

  const ts=(id)=>({padding:"5px 12px",borderRadius:7,border:"none",cursor:"pointer",fontSize:11,fontWeight:tab===id?600:400,background:tab===id?"#1a1a1a":"transparent",color:tab===id?"#fff":"#888",whiteSpace:"nowrap",position:"relative"});

  const renderCell=(emp,date)=>{
    const sc=scheds.find(s=>s.employee_id===emp.id&&s.date===date);
    if(sc){
      if(sc.type==="leave"){const lt=LT[sc.leave_type]||LT.off;return<div style={{background:lt.bg,borderRadius:4,padding:"2px 3px",fontSize:9,position:"relative"}}><div style={{color:lt.c,fontWeight:500}}>{lt.l}{sc.half_day?`(${sc.half_day==="am"?"上":"下"})`:""}</div><button onClick={()=>delSch(sc.id)} style={{position:"absolute",top:0,right:1,background:"none",border:"none",cursor:"pointer",fontSize:8,color:"#ccc"}}>✕</button></div>;}
      return<div style={{background:sc.published?"#e6f9f0":"#fff8e6",borderRadius:4,padding:"2px 3px",fontSize:9,position:"relative"}}><div style={{fontWeight:500}}>{sc.shifts?.name}</div><div style={{color:"#888"}}>{sc.shifts?.start_time?.slice(0,5)}~{sc.shifts?.end_time?.slice(0,5)}</div>{!sc.published&&<span style={{fontSize:7,color:"#8a6d00"}}>未發布</span>}<button onClick={()=>delSch(sc.id)} style={{position:"absolute",top:0,right:1,background:"none",border:"none",cursor:"pointer",fontSize:8,color:"#ccc"}}>✕</button></div>;
    }
    return<select onChange={e=>{const v=e.target.value;e.target.value="";if(!v)return;if(v.startsWith("leave:"))addLv(emp.id,date,v.split(":")[1]);else addSch(emp.id,v,date);}} style={{width:"100%",padding:"1px",borderRadius:3,border:"1px dashed #ddd",fontSize:9,color:"#ccc",background:"transparent",cursor:"pointer"}}><option value="">＋</option><optgroup label="班別">{shifts.filter(s=>!sf||s.store_id===sf).map(s=><option key={s.id} value={s.id}>{s.name} {s.start_time?.slice(0,5)}~{s.end_time?.slice(0,5)}</option>)}</optgroup><optgroup label="休假">{Object.entries(LT).map(([k,v])=><option key={k} value={`leave:${k}`}>{v.l}</option>)}</optgroup></select>;
  };

  return(
    <div style={{minHeight:"100vh",background:"#faf8f5",fontFamily:"system-ui,'Noto Sans TC',sans-serif"}}>
      <div style={{background:"#fff",borderBottom:"1px solid #e8e6e1",padding:"10px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:6}}>
        <div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:18}}>🍯</span><span style={{fontSize:13,fontWeight:600}}>小食糖後台</span></div>
        <div style={{display:"flex",gap:5,flexWrap:"wrap"}}>
          <input type="month" value={month} onChange={e=>setMonth(e.target.value)} style={{padding:"3px 6px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}/>
          <select value={sf} onChange={e=>setSf(e.target.value)} style={{padding:"3px 6px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}><option value="">全部門市</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>
        </div>
      </div>
      <div style={{maxWidth:1200,margin:"0 auto",padding:"12px 8px"}}>
        <div style={{display:"flex",gap:3,marginBottom:10,overflowX:"auto",paddingBottom:3}}>
          {[["schedules","📅排班"],["leaves","🙋請假"],["shifts","⏰班別"],["attendance","📍出勤"],["settings","⚙️設定"],["settlements","💰日結"],["deposits","🏦存款"],["employees","👥員工"]].map(([id,l])=><button key={id} style={ts(id)} onClick={()=>setTab(id)}>{l}{id==="leaves"&&pl.length>0&&<span style={{position:"absolute",top:-3,right:-3,background:"#b91c1c",color:"#fff",borderRadius:"50%",width:14,height:14,fontSize:9,display:"flex",alignItems:"center",justifyContent:"center"}}>{pl.length}</span>}</button>)}
        </div>
        {ld&&<div style={{textAlign:"center",padding:30,color:"#aaa"}}>載入中...</div>}

        {/* 排班 */}
        {!ld&&tab==="schedules"&&<div>
          <div style={{display:"flex",alignItems:"center",gap:5,marginBottom:8,flexWrap:"wrap"}}>
            <button onClick={()=>setSv("week")} style={{padding:"3px 10px",borderRadius:5,border:"1px solid #ddd",background:sv==="week"?"#1a1a1a":"#fff",color:sv==="week"?"#fff":"#666",fontSize:11,cursor:"pointer"}}>週</button>
            <button onClick={()=>setSv("month")} style={{padding:"3px 10px",borderRadius:5,border:"1px solid #ddd",background:sv==="month"?"#1a1a1a":"#fff",color:sv==="month"?"#fff":"#666",fontSize:11,cursor:"pointer"}}>月</button>
            {sv==="week"&&<><button onClick={prevW} style={{padding:"3px 8px",borderRadius:5,border:"1px solid #ddd",background:"#fff",cursor:"pointer",fontSize:11}}>◀</button><span style={{fontSize:12,fontWeight:500}}>{ws}~{wd[6]}</span><button onClick={nextW} style={{padding:"3px 8px",borderRadius:5,border:"1px solid #ddd",background:"#fff",cursor:"pointer",fontSize:11}}>▶</button></>}
            <button onClick={pub} style={{padding:"4px 12px",borderRadius:5,border:"none",background:"#0a7c42",color:"#fff",cursor:"pointer",fontSize:11,marginLeft:"auto"}}>📢 發布</button>
          </div>
          {pm&&<div style={{background:"#e6f9f0",color:"#0a7c42",padding:"5px 10px",borderRadius:5,fontSize:11,marginBottom:6}}>{pm}</div>}

          {sv==="week"&&<div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10,minWidth:700}}><thead><tr style={{background:"#faf8f5",borderBottom:"1px solid #e8e6e1"}}><th style={{padding:"7px 5px",textAlign:"left",fontWeight:500,color:"#666",minWidth:60,position:"sticky",left:0,background:"#faf8f5",zIndex:1}}>員工</th>{wd.map((d,i)=><th key={d} style={{padding:"7px 3px",textAlign:"center",fontWeight:500,color:i===0||i===6?"#b91c1c":"#666",minWidth:85}}>{d.slice(5)}<br/>({DAYS[new Date(d).getDay()]})</th>)}</tr></thead><tbody>{fe.map(emp=><tr key={emp.id} style={{borderBottom:"1px solid #f0eeea"}}><td style={{padding:"5px",fontWeight:500,fontSize:11,position:"sticky",left:0,background:"#fff",zIndex:1}}>{emp.name}<br/><RB role={emp.role}/></td>{wd.map(date=><td key={date} style={{padding:"2px",textAlign:"center",verticalAlign:"top"}}>{renderCell(emp,date)}</td>)}</tr>)}</tbody></table></div>}

          {sv==="month"&&<div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10,tableLayout:"fixed"}}><thead><tr style={{background:"#faf8f5"}}>{DAYS.map((d,i)=><th key={d} style={{padding:"6px 3px",textAlign:"center",color:i===0||i===6?"#b91c1c":"#666",fontWeight:500}}>{d}</th>)}</tr></thead><tbody>{Array.from({length:6},(_,wk)=>{const md=getMD();const row=md.slice(wk*7,wk*7+7);if(!row.length||!row.some(d=>d.inM))return null;return<tr key={wk}>{row.map(({date,inM})=>{const ds=scheds.filter(s=>s.date===date);return<td key={date} style={{padding:3,verticalAlign:"top",border:"1px solid #f0eeea",minHeight:50,opacity:inM?1:0.3}}><div style={{fontSize:10,fontWeight:500,color:"#666",marginBottom:1}}>{parseInt(date.split("-")[2])}</div>{ds.slice(0,3).map(s=>{if(s.type==="leave"){const lt=LT[s.leave_type]||LT.off;return<div key={s.id} style={{background:lt.bg,borderRadius:2,padding:"0 2px",fontSize:8,marginBottom:1,color:lt.c,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis"}}>{s.employees?.name} {lt.l}</div>;}return<div key={s.id} style={{background:s.published?"#e6f9f0":"#fff8e6",borderRadius:2,padding:"0 2px",fontSize:8,marginBottom:1,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis"}}>{s.employees?.name} {s.shifts?.name}</div>;})}{ds.length>3&&<div style={{fontSize:8,color:"#999"}}>+{ds.length-3}</div>}</td>;})}</tr>;})}</tbody></table></div>}
        </div>}

        {/* 請假 */}
        {!ld&&tab==="leaves"&&<div>
          {pl.length>0&&<div style={{background:"#fff8e6",border:"1px solid #fbbf2440",borderRadius:8,padding:12,marginBottom:10}}><h3 style={{fontSize:13,fontWeight:500,marginBottom:8}}>⏳ 待審核（{pl.length}）</h3>{pl.map(l=><div key={l.id} style={{display:"flex",alignItems:"center",gap:8,padding:"6px 0",borderBottom:"1px solid #f0eeea",flexWrap:"wrap"}}><span style={{fontWeight:500,fontSize:12}}>{l.employees?.name}</span><span style={{fontSize:11,color:LT[l.leave_type]?.c}}>{LT[l.leave_type]?.l}</span><span style={{fontSize:11}}>{l.start_date}{l.end_date!==l.start_date?` ~ ${l.end_date}`:""}{l.half_day?`（${l.half_day==="am"?"上午":"下午"}）`:""}</span><div style={{marginLeft:"auto",display:"flex",gap:3}}><button onClick={()=>rvLv(l.id,"approved")} style={{padding:"3px 10px",borderRadius:5,border:"none",background:"#0a7c42",color:"#fff",fontSize:11,cursor:"pointer"}}>✅核准</button><button onClick={()=>rvLv(l.id,"rejected")} style={{padding:"3px 10px",borderRadius:5,border:"none",background:"#b91c1c",color:"#fff",fontSize:11,cursor:"pointer"}}>❌駁回</button></div></div>)}</div>}
          <div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#faf8f5",borderBottom:"1px solid #e8e6e1"}}>{["員工","假別","日期","半天","狀態","時間"].map(h=><th key={h} style={{padding:7,textAlign:"left",fontWeight:500,color:"#666"}}>{h}</th>)}</tr></thead><tbody>{lr.map(l=><tr key={l.id} style={{borderBottom:"1px solid #f0eeea"}}><td style={{padding:7,fontWeight:500}}>{l.employees?.name}</td><td style={{padding:7,color:LT[l.leave_type]?.c}}>{LT[l.leave_type]?.l||l.leave_type}</td><td style={{padding:7}}>{l.start_date}{l.end_date!==l.start_date?`~${l.end_date}`:""}</td><td style={{padding:7}}>{l.half_day?l.half_day==="am"?"上午":"下午":"全日"}</td><td style={{padding:7}}><Badge status={l.status}/></td><td style={{padding:7,fontSize:10,color:"#888"}}>{new Date(l.created_at).toLocaleString("zh-TW",{timeZone:"Asia/Taipei",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</td></tr>)}</tbody></table></div>
        </div>}

        {/* 班別 */}
        {!ld&&tab==="shifts"&&<div>
          <button onClick={()=>{setSsf(!ssf);setEs(null);setSf2({store_id:"",name:"",start_time:"10:00",end_time:"20:00",break_minutes:60,work_hours:9,role:"all"});}} style={{padding:"5px 14px",borderRadius:6,border:"1px solid #ddd",background:ssf?"#f0f0f0":"#1a1a1a",color:ssf?"#666":"#fff",fontSize:11,cursor:"pointer",marginBottom:8}}>{ssf?"✕":"＋ 新增"}</button>
          {ssf&&<div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",padding:14,marginBottom:8}}><div style={{fontSize:12,fontWeight:500,marginBottom:8}}>{es?"✏️ 編輯":"＋ 新增"}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:8}}>{[["store_id","門市","select"],["name","名稱","text"],["role","角色","role"],["start_time","上班","time"],["end_time","下班","time"],["break_minutes","休息(分)","number"]].map(([k,l,t])=><div key={k}><label style={{fontSize:10,color:"#888"}}>{l}</label>{t==="select"?<select value={sf2[k]} onChange={e=>setSf2({...sf2,[k]:e.target.value})} style={{width:"100%",padding:"5px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}><option value="">選擇</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>:t==="role"?<select value={sf2[k]} onChange={e=>setSf2({...sf2,[k]:e.target.value})} style={{width:"100%",padding:"5px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}><option value="all">全場</option><option value="外場">外場</option><option value="內場">內場</option></select>:<input type={t} value={sf2[k]} onChange={e=>setSf2({...sf2,[k]:t==="number"?Number(e.target.value):e.target.value})} style={{width:"100%",padding:"5px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}/>}</div>)}</div><button onClick={saveShift} style={{padding:"5px 16px",borderRadius:5,border:"none",background:"#0a7c42",color:"#fff",fontSize:11,cursor:"pointer"}}>{es?"💾 儲存":"建立"}</button></div>}
          <div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#faf8f5",borderBottom:"1px solid #e8e6e1"}}>{["門市","班別","時間","休息","角色","操作"].map(h=><th key={h} style={{padding:7,textAlign:"left",fontWeight:500,color:"#666"}}>{h}</th>)}</tr></thead><tbody>{shifts.map(s=><tr key={s.id} style={{borderBottom:"1px solid #f0eeea"}}><td style={{padding:7}}>{s.stores?.name}</td><td style={{padding:7,fontWeight:500}}>{s.name}</td><td style={{padding:7}}>{s.start_time?.slice(0,5)}~{s.end_time?.slice(0,5)}</td><td style={{padding:7}}>{s.break_minutes}分</td><td style={{padding:7}}>{s.role}</td><td style={{padding:7}}><button onClick={()=>editShift(s)} style={{padding:"1px 6px",borderRadius:3,border:"1px solid #ddd",background:"transparent",cursor:"pointer",fontSize:10,marginRight:3}}>✏️</button><button onClick={()=>delShift(s.id)} style={{padding:"1px 6px",borderRadius:3,border:"1px solid #ddd",background:"transparent",cursor:"pointer",fontSize:10,color:"#b91c1c"}}>🗑</button></td></tr>)}</tbody></table></div>
        </div>}

        {/* 出勤 */}
        {!ld&&tab==="attendance"&&<div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11,minWidth:600}}><thead><tr style={{background:"#faf8f5",borderBottom:"1px solid #e8e6e1"}}>{["時間","員工","門市","類型","距離","遲到"].map(h=><th key={h} style={{padding:7,textAlign:"left",fontWeight:500,color:"#666"}}>{h}</th>)}</tr></thead><tbody>{att.map(a=><tr key={a.id} style={{borderBottom:"1px solid #f0eeea"}}><td style={{padding:7,fontSize:10}}>{new Date(a.timestamp).toLocaleString("zh-TW",{timeZone:"Asia/Taipei",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</td><td style={{padding:7,fontWeight:500}}>{a.employees?.name}</td><td style={{padding:7}}>{a.stores?.name}</td><td style={{padding:7}}>{a.type==="clock_in"?"🟢上班":"🔴下班"}</td><td style={{padding:7}}>{a.distance_meters?`${Math.round(a.distance_meters)}m`:"-"}{a.is_valid?"✅":"❌"}</td><td style={{padding:7,color:a.late_minutes>0?"#b91c1c":"#0a7c42"}}>{a.late_minutes>0?`${a.late_minutes}分`:"準時"}</td></tr>)}</tbody></table></div>}

        {/* 設定 */}
        {!ld&&tab==="settings"&&<div style={{maxWidth:420}}><div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",padding:14}}><h3 style={{fontSize:13,fontWeight:500,marginBottom:10}}>⚙️ 打卡設定</h3>{[["late_grace_minutes","遲到寬限(分)"],["late_threshold_minutes","嚴重遲到(分)"],["early_leave_minutes","早退認定(分)"],["overtime_min_minutes","加班最低(分)"],["work_hours_per_day","每日工時"],["work_hours_per_week","每週工時"]].map(([k,l])=><div key={k} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"6px 0",borderBottom:"1px solid #f0eeea"}}><span style={{fontSize:12}}>{l}</span><input type="number" value={as[k]??""} onChange={e=>upS(k,Number(e.target.value))} style={{width:55,padding:4,borderRadius:5,border:"1px solid #ddd",textAlign:"center",fontSize:12}}/></div>)}</div></div>}

        {/* 日結 */}
        {!ld&&tab==="settlements"&&<div><div style={{display:"flex",gap:6,marginBottom:10}}><div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",padding:"8px 14px",flex:1}}><div style={{fontSize:10,color:"#888"}}>淨額</div><div style={{fontSize:16,fontWeight:600,color:"#0a7c42"}}>{fmt(sum.total_net_sales)}</div></div><div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",padding:"8px 14px",flex:1}}><div style={{fontSize:10,color:"#888"}}>應存</div><div style={{fontSize:16,fontWeight:600,color:"#b45309"}}>{fmt(sum.total_cash_to_deposit)}</div></div></div><div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#faf8f5",borderBottom:"1px solid #e8e6e1"}}>{["日期","門市","淨額","現金","應存","📷"].map(h=><th key={h} style={{padding:"7px 5px",textAlign:"left",fontWeight:500,color:"#666"}}>{h}</th>)}</tr></thead><tbody>{stl.map(s=><tr key={s.id} style={{borderBottom:"1px solid #f0eeea"}}><td style={{padding:"7px 5px"}}>{s.date}</td><td style={{padding:"7px 5px",fontWeight:500}}>{s.stores?.name}</td><td style={{padding:"7px 5px",color:"#0a7c42",fontWeight:600}}>{fmt(s.net_sales)}</td><td style={{padding:"7px 5px"}}>{fmt(s.cash_amount)}</td><td style={{padding:"7px 5px",color:"#b45309"}}>{fmt(s.cash_to_deposit)}</td><td style={{padding:"7px 5px"}}>{s.image_url&&<button onClick={()=>setSi(s.image_url)} style={{padding:"1px 5px",borderRadius:3,border:"1px solid #ddd",background:"transparent",cursor:"pointer",fontSize:9}}>📷</button>}</td></tr>)}</tbody></table></div></div>}

        {/* 存款 */}
        {!ld&&tab==="deposits"&&<div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#faf8f5",borderBottom:"1px solid #e8e6e1"}}>{["日期","門市","金額","應存","差異","狀態"].map(h=><th key={h} style={{padding:7,textAlign:"left",fontWeight:500,color:"#666"}}>{h}</th>)}</tr></thead><tbody>{dep.map(d=><tr key={d.id} style={{borderBottom:"1px solid #f0eeea"}}><td style={{padding:7}}>{d.deposit_date}</td><td style={{padding:7,fontWeight:500}}>{d.stores?.name}</td><td style={{padding:7,fontWeight:600}}>{fmt(d.amount)}</td><td style={{padding:7}}>{fmt(d.expected_cash)}</td><td style={{padding:7,color:Math.abs(d.difference)<=500?"#0a7c42":"#b91c1c"}}>{d.difference>=0?"+":""}{fmt(d.difference)}</td><td style={{padding:7}}><Badge status={d.status}/></td></tr>)}</tbody></table></div>}

        {/* 員工 */}
        {!ld&&tab==="employees"&&<div><button onClick={()=>{setSaf(!saf);setNbc(null);}} style={{padding:"5px 14px",borderRadius:6,border:"1px solid #ddd",background:saf?"#f0f0f0":"#1a1a1a",color:saf?"#666":"#fff",fontSize:11,cursor:"pointer",marginBottom:8}}>{saf?"✕":"＋新增"}</button>{saf&&<div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",padding:14,marginBottom:8}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginBottom:8}}><div><label style={{fontSize:10,color:"#888"}}>姓名*</label><input value={ne.name} onChange={e=>setNe({...ne,name:e.target.value})} style={{width:"100%",padding:"5px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}/></div><div><label style={{fontSize:10,color:"#888"}}>門市</label><select value={ne.store_id} onChange={e=>setNe({...ne,store_id:e.target.value})} style={{width:"100%",padding:"5px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}><option value="">總部</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label style={{fontSize:10,color:"#888"}}>角色</label><select value={ne.role} onChange={e=>setNe({...ne,role:e.target.value})} style={{width:"100%",padding:"5px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}><option value="staff">員工</option><option value="manager">管理</option><option value="admin">總部</option></select></div><div><label style={{fontSize:10,color:"#888"}}>電話</label><input value={ne.phone} onChange={e=>setNe({...ne,phone:e.target.value})} style={{width:"100%",padding:"5px",borderRadius:5,border:"1px solid #ddd",fontSize:11}}/></div></div><button onClick={addEmp} disabled={!ne.name} style={{padding:"5px 14px",borderRadius:5,border:"none",background:ne.name?"#0a7c42":"#ccc",color:"#fff",fontSize:11,cursor:"pointer"}}>建立</button>{nbc&&<div style={{marginTop:6,padding:8,background:"#e6f9f0",borderRadius:5,fontSize:12}}><b style={{color:"#0a7c42"}}>綁定碼：{nbc}</b><br/><span style={{fontSize:10}}>員工輸入：綁定 {nbc}</span></div>}</div>}<div style={{background:"#fff",borderRadius:8,border:"1px solid #e8e6e1",overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#faf8f5",borderBottom:"1px solid #e8e6e1"}}>{["姓名","角色","門市","LINE","操作"].map(h=><th key={h} style={{padding:7,textAlign:"left",fontWeight:500,color:"#666"}}>{h}</th>)}</tr></thead><tbody>{emps.map(e=><tr key={e.id} style={{borderBottom:"1px solid #f0eeea",opacity:e.is_active?1:0.4}}><td style={{padding:7,fontWeight:500}}>{e.name}</td><td style={{padding:7}}><RB role={e.role}/></td><td style={{padding:7}}>{e.stores?.name||"總部"}</td><td style={{padding:7}}>{e.line_uid?<span style={{color:"#0a7c42"}}>✅</span>:<span style={{fontSize:10}}>{e.bind_code||"未綁"}</span>}</td><td style={{padding:7}}>{!e.line_uid&&<button onClick={()=>regen(e.id)} style={{padding:"1px 6px",borderRadius:3,border:"1px solid #ddd",background:"transparent",cursor:"pointer",fontSize:9}}>🔄</button>}</td></tr>)}</tbody></table></div></div>}
      </div>
      {si&&<div onClick={()=>setSi(null)} style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.7)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:9999,cursor:"pointer",padding:12}}><img src={si} alt="" style={{maxWidth:"90vw",maxHeight:"85vh",borderRadius:8}}/></div>}
    </div>
  );
}
